name: Push-to-EC2

# Trigger deployment only on push to gitaction-dev branch
on:
  push:
    branches:
      - gitaction-dev

jobs:
  deploy:
    name: Deploy to EC2 on gitaction-dev branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Deploy to ec2 using SSH commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            git fetch
            git reset --hard origin/gitaction-dev
            pip install -U -r requirements.txt
            echo ("finished!")
            exit 0
            
